import hashlib
from pathlib import Path

from dataclasses import dataclass

from agentscope.tool import FunctionTool
from agentscope.rag import KnowledgeBase
from sqlalchemy.ext.asyncio import (
    AsyncEngine,
    async_sessionmaker,
)

from app.application.memory.preference_selector import (
    PreferenceSelector,
)
from app.application.tools.preference_tools import (
    build_forget_preference_tool,
    build_remember_preference_tool,
)
from app.domain.buyer.ports.preference_store import (
    PreferenceStore,
)
from app.infrastructure.cache.semantic_cache import (
    SemanticCache,
)
from app.infrastructure.persistence.sql.sql_preference_store import (
    SqlPreferenceStore,
)
from app.infrastructure.persistence.sql.database import (
    bootstrap_schema,
    create_database_engine,
)
from app.infrastructure.persistence.sql.sql_conversation_store import (
    SqlConversationStore,
)
from app.infrastructure.persistence.sql.sql_session_store import (
    SqlSessionStore,
)
from app.domain.catalog.ports.retrieval_ports import (
    EmbeddingClient,
)
from app.domain.session.ports.conversation_store import (
    ConversationStore,
)
from app.infrastructure.cache.redis_cache import RedisCache
from app.infrastructure.cache.redis_idempotency import (
    RedisIdempotency,
)
from app.infrastructure.cache.cached_embedding_client import (
    CachedEmbeddingClient,
)
from app.infrastructure.embedding.openai_embedding_client import (
    OpenAIEmbeddingClient,
)
from app.infrastructure.vector.index_bootstrap import (
    bootstrap_product_index,
)
from app.infrastructure.vector.qdrant_product_index import (
    QdrantProductIndex,
)
from app.infrastructure.rag.category_knowledge import (
    bootstrap_category_knowledge,
    build_category_knowledge_base,
)
from app.infrastructure.rerank.http_reranker import (
    HttpReranker,
)
from app.infrastructure.eventbus import (
    InMemoryTradeEventBus,
)
from app.application.agents.main_agent import MainAgentFactory
from app.application.agents.orchestrator import (
    MainAgentOrchestrator,
)
from app.application.agents.search_agent import (
    SearchAgentFactory,
)
from app.application.agents.trade_agent import (
    TradeAgentFactory,
)
from app.application.tools.task_dispatch_tool import (
    build_task_dispatch_tool,
)
from app.application.usecases.catalog_search import (
    CatalogSearchUseCase,
)
from app.application.usecases.cancel_order import (
    CancelOrderUseCase,
)
from app.application.usecases.place_order import (
    PlaceOrderUseCase,
)
from app.application.usecases.query_order import (
    QueryOrderUseCase,
)
from app.application.agents.session_registry import (
    SessionRegistry,
)
from app.application.usecases.get_conversation_history import (
    GetConversationHistoryUseCase,
)
from app.application.usecases.enqueue_intent import (
    EnqueueIntentUseCase,
    GetTaskStatusUseCase,
)
from app.domain.catalog.ports.product_repository import (
    ProductRepository,
)
from app.domain.order.ports.order_repository import (
    OrderRepository,
)
from app.domain.queue.ports.task_queue import TaskQueue
from app.infrastructure.llm import create_chat_model
from app.infrastructure.persistence.in_memory_product_repository import (
    InMemoryProductRepository,
)
from app.infrastructure.persistence.seed_products import (
    build_seed_products,
)
from app.infrastructure.persistence.in_memory_order_repository import (
    InMemoryOrderRepository,
)
from app.infrastructure.queue.redis_stream_queue import (
    RedisStreamTaskQueue,
)
from app.infrastructure.queue.redis_event_backplane import (
    RedisEventBackplane,
)
from app.application.events import EventBackplane
from app.infrastructure.settings import Settings, load_settings


def _main_agent_source_fingerprint() -> str:
    """
    Fingerprint MainAgent behavior for semantic cache isolation.

    Any MainAgent prompt or configuration change invalidates replies
    generated by the previous version.
    """

    source_path = (
        Path(__file__).resolve().parent
        / "application"
        / "agents"
        / "main_agent.py"
    )

    return hashlib.sha256(
        source_path.read_bytes()
    ).hexdigest()[:16]


@dataclass
class Container:
    settings: Settings
    main_agent_factory: MainAgentFactory
    search_agent_factory: SearchAgentFactory
    trade_agent_factory: TradeAgentFactory
    sessions: SessionRegistry
    orchestrator: MainAgentOrchestrator

    product_repository: ProductRepository
    order_repository: OrderRepository
    knowledge_base: KnowledgeBase

    event_bus: InMemoryTradeEventBus
    event_backplane: EventBackplane | None
    cache: RedisCache
    semantic_cache: SemanticCache
    task_queue: TaskQueue | None
    idempotency: RedisIdempotency | None
    enqueue_intent: EnqueueIntentUseCase | None
    get_task_status: GetTaskStatusUseCase | None
    conversation_store: ConversationStore
    preference_store: PreferenceStore
    get_conversation_history: GetConversationHistoryUseCase
    database_engine: AsyncEngine

    catalog_search: CatalogSearchUseCase
    place_order: PlaceOrderUseCase
    query_order: QueryOrderUseCase
    cancel_order: CancelOrderUseCase

    embedder: EmbeddingClient
    vector_index: QdrantProductIndex
    # The container is the only place where it knows every module

    async def startup(self) -> None:
        """Initialize external resources and searchable data."""
        if self.task_queue is not None:
            await self.task_queue.ensure_ready()

        await bootstrap_schema(
            self.database_engine,
        )

        await self.knowledge_base.vector_store.__aenter__()

        await bootstrap_product_index(
            product_repository=self.product_repository,
            embedder=self.embedder,
            vector_index=self.vector_index,
            embedder_namespace=(
                f"{self.settings.embedding_base_url.rstrip('/')}|"
                f"{self.settings.embedding_model}|"
                "product-vector-v1"
            ),
        )

        await bootstrap_category_knowledge(
            self.knowledge_base,
        )

    async def shutdown(self) -> None:
        """Release external resources."""

        try:
            await self.vector_index.close()
        finally:
            try:
                await self.knowledge_base.vector_store.__aexit__(
                    None,
                    None,
                    None,
                )
            finally:
                try:
                    await self.event_bus.drain()
                finally:
                    try:
                        await self.cache.close()
                    finally:
                        await self.database_engine.dispose()


def build_container() -> Container:
    settings = load_settings()

    cache = RedisCache(
        settings.redis_url,
    )

    task_queue: TaskQueue | None = None
    idempotency: RedisIdempotency | None = None
    enqueue_intent: EnqueueIntentUseCase | None = None
    get_task_status: GetTaskStatusUseCase | None = None
    event_backplane: EventBackplane | None = None

    if settings.queue_enabled:
        redis_client = cache.client

        if redis_client is None:
            raise RuntimeError(
                "Task queue is enabled but Redis is unavailable"
            )

        task_queue = RedisStreamTaskQueue(
            redis_client
        )
        idempotency = RedisIdempotency(redis_client)
        event_backplane = RedisEventBackplane(redis_client)

    database_engine = create_database_engine(
        settings.database_url,
    )

    session_factory = async_sessionmaker(
        database_engine,
        expire_on_commit=False,
    )

    raw_embedder = OpenAIEmbeddingClient(settings)

    embedder: EmbeddingClient = (
        CachedEmbeddingClient(
            inner=raw_embedder,
            cache=cache,
            model=settings.embedding_model,
        )
        if cache.enabled
        else raw_embedder
    )  # redis cache or raw embedding option

    semantic_cache = SemanticCache(
        cache=cache,
        embedder=embedder,
        threshold=(
            settings.semantic_cache_threshold
        ),
        enabled=settings.semantic_cache_enabled,
        namespace=(
            f"chat={settings.llm_model}:"
            f"embedding={settings.embedding_model}:"
            f"prompt={_main_agent_source_fingerprint()}"
        ),
    )

    vector_index = QdrantProductIndex(settings)

    reranker = (
        HttpReranker(settings)
        if settings.reranker_base_url
        else None
    )

    knowledge_base = build_category_knowledge_base(
        settings,
    )

    product_repository = InMemoryProductRepository(
        build_seed_products(),
    )

    catalog_search = CatalogSearchUseCase(
        product_repository,
        embedder=embedder,
        vector_index=vector_index,
        reranker=reranker,
    )

    order_repository = InMemoryOrderRepository()

    place_order = PlaceOrderUseCase(
        product_repository=product_repository,
        order_repository=order_repository,
    )

    query_order = QueryOrderUseCase(
        order_repository=order_repository,
    )

    cancel_order = CancelOrderUseCase(
        product_repository=product_repository,
        order_repository=order_repository,
    )

    model = create_chat_model(settings)

    search_agent_factory = SearchAgentFactory(
        model=model,
        catalog_search=catalog_search,
        knowledge_base=knowledge_base,
    )

    trade_agent_factory = TradeAgentFactory(
        model=model,
        place_order=place_order,
        query_order=query_order,
        cancel_order=cancel_order,
    )

    event_bus = InMemoryTradeEventBus(event_backplane)

    preference_store = SqlPreferenceStore(
        session_factory,
    )

    preference_selector = PreferenceSelector(
        embedder=embedder,
        relevance_enabled=(
            settings.preference_relevance_enabled
        ),
    )

    remember_preference_function = (
        build_remember_preference_tool(
            store=preference_store,
            event_publisher=event_bus,
        )
    )
    remember_preference_tool = FunctionTool(
        remember_preference_function,
        is_read_only=False,
    )

    forget_preference_function = (
        build_forget_preference_tool(
            store=preference_store,
            event_publisher=event_bus,
        )
    )
    forget_preference_tool = FunctionTool(
        forget_preference_function,
        is_read_only=False,
    )

    task_dispatch_function = build_task_dispatch_tool(
        search_factory=search_agent_factory,
        trade_factory=trade_agent_factory,
        preference_store=preference_store,
        preference_selector=preference_selector,
        preference_top_k=settings.preference_top_k,
        inject_preferences=(
            settings.preference_subagent_inject
        ),
    )
    task_dispatch_tool = FunctionTool(
        task_dispatch_function,
        is_read_only=False,
    )

    main_agent_factory = MainAgentFactory(
        model=model,
        tools=[
            *search_agent_factory.build_tools(),
            *trade_agent_factory.build_tools(),
            remember_preference_tool,
            forget_preference_tool,
            task_dispatch_tool,
        ],
    )

    session_store = SqlSessionStore(
        session_factory,
    )

    sessions = SessionRegistry(
        main_agent_factory=main_agent_factory,
        session_store=session_store,
    )

    conversation_store = SqlConversationStore(
        session_factory,
    )

    get_conversation_history = GetConversationHistoryUseCase(
        conversation_store=conversation_store,
    )

    orchestrator = MainAgentOrchestrator(
        sessions=sessions,
        event_bus=event_bus,
        conversation_store=conversation_store,
        semantic_cache=semantic_cache,
        preference_store=preference_store,
        preference_selector=preference_selector,
        preference_top_k=settings.preference_top_k,
    )

    if task_queue is not None and idempotency is not None:
        enqueue_intent = EnqueueIntentUseCase(
            task_queue=task_queue,
            idempotency=idempotency,
            conversation_store=conversation_store,
            event_publisher=event_bus,
            priority_enabled=settings.queue_priority_enabled,
            large_request_turns=settings.queue_large_request_turns,
        )
        get_task_status = GetTaskStatusUseCase(task_queue)

    return Container(
        settings=settings,
        main_agent_factory=main_agent_factory,
        search_agent_factory=search_agent_factory,
        trade_agent_factory=trade_agent_factory,
        embedder=embedder,
        vector_index=vector_index,
        knowledge_base=knowledge_base,
        event_bus=event_bus,
        event_backplane=event_backplane,
        cache=cache,
        semantic_cache=semantic_cache,
        task_queue=task_queue,
        idempotency=idempotency,
        enqueue_intent=enqueue_intent,
        get_task_status=get_task_status,
        conversation_store=conversation_store,
        preference_store=preference_store,
        database_engine=database_engine,
        get_conversation_history=get_conversation_history,
        sessions=sessions,
        orchestrator=orchestrator,
        product_repository=product_repository,
        order_repository=order_repository,
        catalog_search=catalog_search,
        place_order=place_order,
        query_order=query_order,
        cancel_order=cancel_order,
    )
